### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by orillero** [akvadrako/site-xyz#11]
![Footer1](https://github.com/akvadrako/site-xyz/assets/98652759/2f2d8b07-7d02-48ab-9d6d-4fbb7b1a1f83)

**Comment by akvadrako** [comment]
So 48 is what? And 96 is margin above and below footer?

**Comment by orillero** [comment]
I will use these names for the 2 dominant colours:
Ambergris: 3d3732 (orange tinted dark gray)
Sandstone: f2ede8 (orange tinted white).

**Comment by akvadrako** [comment]
Should be ready.
