### ISSUE TITLE
Work laptop view 1

### ISSUE THREAD

**Issue by orillero** [akvadrako/site-xyz#13]
![Works laptop1](https://github.com/akvadrako/site-xyz/assets/98652759/9e6060be-e10f-47b9-9abb-82724a24f3ea)

**Comment by akvadrako** [comment]
Seems nice. And the horizontal spacing?

**Comment by akvadrako** [comment]
I changed it but I'm not sure it's what you want. When the window is tall and narrow there is a lot of empty space for landscape photos.
