### ISSUE TITLE
Work_phone

### ISSUE THREAD

**Issue by orillero** [akvadrako/site-xyz#14]
![Works_Phone](https://github.com/akvadrako/site-xyz/assets/98652759/82898e45-2813-4609-98e3-529bcd83b16d)

**Comment by akvadrako** [comment]
should be ready

**Comment by orillero** [comment]
![Works_Phone2](https://github.com/akvadrako/site-xyz/assets/98652759/c114cd93-113f-4e39-812a-cd78df2fb4a4)
