### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by orillero** [akvadrako/site-xyz#18]
<img width="1279" alt="1 About" src="https://github.com/user-attachments/assets/e46fb321-cba8-4eeb-86d9-76f549ebd336">
![2 About section](https://github.com/user-attachments/assets/074047b0-ef47-4722-8e48-af83702059b6)
[About.docx](https://github.com/user-attachments/files/17031922/About.docx)

**Comment by akvadrako** [comment]
okay.
