### ISSUE TITLE
Works

### ISSUE THREAD

**Issue by orillero** [akvadrako/site-xyz#3]
![Works01](https://github.com/akvadrako/site-xyz/assets/98652759/21f52477-2766-4d68-a91b-16b93c701879)
![Works02](https://github.com/akvadrako/site-xyz/assets/98652759/eb3cda0e-eb66-4c43-81e7-8ec03b7349ac)
![Works03](https://github.com/akvadrako/site-xyz/assets/98652759/bc633671-2ec7-436f-a38b-a27f1a766960)
![Works04](https://github.com/akvadrako/site-xyz/assets/98652759/f6721321-d5a2-4b57-a60b-4e653ca68dee)
![Works05 next prev](https://github.com/akvadrako/site-xyz/assets/98652759/3d718f96-f7a0-4788-8681-49cc417e4639)
![Works06](https://github.com/akvadrako/site-xyz/assets/98652759/9131642a-6464-4862-97ae-4d9ac35f3b43)

**Comment by akvadrako** [comment]
First part fixed.

**Comment by akvadrako** [comment]
Second part fixed.

**Comment by akvadrako** [comment]
Last bug fixed.

**Comment by akvadrako** [comment]
Created new issue #10 for sub-image browser.
